# Environment Variables
@host = localhost
@port = 3000
@baseUrl = http://{{host}}:{{port}}

@coffeesApiUrl = {{baseUrl}}/coffees

### Get all coffees Request - /
GET {{coffeesApiUrl}} HTTP/1.1


### Get One Coffee
GET {{coffeesApiUrl}}/id-xsdfs HTTP/1.1