# Environment Variables
@host = localhost
@port = 3000
@baseUrl = http://{{host}}:{{port}}
@coffeesApiUrl = {{baseUrl}}/coffees
@jsonContent = application/json

### Get all coffees Request - /
GET {{coffeesApiUrl}} HTTP/1.1


### Get One Coffee
GET {{coffeesApiUrl}}/id-xsdfs HTTP/1.1

### Create a coffee entry
POST {{coffeesApiUrl}} HTTP/1.1
Content-Type: {{jsonContent}}

{
  "name": "Kenya Roasted Coffee",
  "brand": "Buddy Brew"
}

### Update a coffee given coffee id
PATCH {{coffeesApiUrl}}/2 HTTP/1.1
Content-Type: {{jsonContent}}

{
  "name": "Updated Kenya Roasted Coffee"
}

### Delete a Coffee Entry Given an Id
DELETE {{coffeesApiUrl}}/2 HTTP/1.1
