# Environment Variables
@host = localhost
@port = 3000
@baseUrl = http://{{host}}:{{port}}
@coffeesApiUrl = {{baseUrl}}/coffees
@jsonContent = application/json

### Get all coffees Request - /
GET {{coffeesApiUrl}} HTTP/1.1


### Get Paginated coffees Request/?offset=&limit=
GET {{coffeesApiUrl}}/?offset=2&limit=10 HTTP/1.1

### Get One Coffee
GET {{coffeesApiUrl}}/11bf5b37-e0b8-42e0-8dcf-dc8c4aefc000 HTTP/1.1

### Create a coffee entry
POST {{coffeesApiUrl}} HTTP/1.1
Content-Type: {{jsonContent}}

{
  "name": "Kenya Roasted Coffee",
  "brand": "Buddy Brew",
  "flavors": ["Highland Vanilla", "Lowland Butter"]
}

### Update a coffee given coffee id
PATCH {{coffeesApiUrl}}/48078c68-27cd-4a74-95e2-c823f7327417 HTTP/1.1
Content-Type: {{jsonContent}}

{
  "name": "Updated Kenya Roasted Coffee"
}

### Delete a Coffee Entry Given an Id
DELETE {{coffeesApiUrl}}/dd105cb5-e878-42ab-9f55-b9eefc81a707 HTTP/1.1
