services:
  db:
    image: postgres:alpine
    restart: always
    container_name: cf-gql-schema-cnt
    ports:
      - "5434:5432"
    env_file:
      - ./dev.env
    volumes:
      - pg-data:/var/lib/postgresql/data

  client: 
    image: adminer
    restart: always
    ports: 
      - "8081:8080"
    environment:
      - ADMINER_DESIGN=dracula

volumes:
  pg-data:
